_G.servers = {
	lua_ls = "lua",
	cssls = "css",
	html = "html",
	tsserver = "typescript",
	pyright = "python",
	bashls = "bash",
	jsonls = "json",
	yamlls = "yaml",
	jdtls = "java",
	rust_analyzer = "rust",
	clangd = "clang",
}

_G.kinds = {
	Text = "󰉿",
	Method = "󰊕",
	Function = "󰊕",
	Constructor = "",
	Field = "α",
	Variable = "α",
	Class = "󰌗",
	Interface = "",
	Module = "󰅩",
	Namespace = "󰅩",
	Property = "",
	Unit = "",
	Value = "󰎠",
	Enum = "",
	EnumMember = "",
	Keyword = "",
	Snippet = "",
	Color = "󰏘",
	File = "󰈙",
	Reference = "",
	Folder = "󰉖",
	Constant = "π",
	Struct = "",
	Event = "ϟ",
	Operator = "󰆕",
	TypeParameter = "τ",
	Package = "",
	String = '󰉾""',
	Number = "λ",
	Boolean = "",
	Array = "󰅪",
	Object = "󰅩",
	Key = "",
	Null = "∅",
}

_G.signs = {
	error = "",
	warn = "",
	hint = "󰛨",
	info = "",
}

_G.symbols = {
	modified = "",
	readonly = "",
	newfile = "",
	unnamed = "",
	ellipsis = "…",
	separator = "",
}
