_G.servers = {
	lua = "lua_ls",
	css = "cssls",
	html = "html",
	typescript = "tsserver",
	python = "pyright",
	bash = "bashls",
	json = "jsonls",
	yaml = "yamlls",
	rust = "rust_analyzer",
	c = "clangd",
}

_G.kinds = {
	Text = "󰉿",
	Method = "",
	Function = "󰊕",
	Constructor = "",
	Field = "",
	Variable = "α",
	Class = "󰌗",
	Interface = "",
	Module = "󰅩",
	Namespace = "󰅩",
	Property = "",
	Unit = "",
	Value = "󰎠",
	Enum = "",
	EnumMember = "",
	Keyword = "",
	Snippet = "",
	Color = "󰏘",
	File = "󰈙",
	Reference = "",
	Folder = "󰉖",
	Constant = "π",
	Struct = "",
	Event = "ϟ",
	Operator = "󰆕",
	TypeParameter = "τ",
	Package = "",
	String = "󰉾",
	Number = "λ",
	Boolean = "",
	Array = "󰅪",
	Object = "󰅩",
	Key = "",
	Null = "∅",
}

_G.signs = {
	error = "",
	warn = "",
	hint = "󰛨",
	info = "",
}

_G.symbols = {
	modified = "",
	readonly = "",
	newfile = "",
	unnamed = "",
	ellipsis = "…",
	separator = "",
}
